// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEze1hNc0QxtG3PPqiY6MbXGvaBnQP8Cs',
    appId: '1:300459782788:web:3b071b982d184ebcd788d1',
    messagingSenderId: '300459782788',
    projectId: 'prueba-66e48',
    authDomain: 'prueba-66e48.firebaseapp.com',
    storageBucket: 'prueba-66e48.appspot.com',
    measurementId: 'G-CJEBKFMEZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN3z3OTYCI0AfNcTqwTAoaNAoYUB1SYGQ',
    appId: '1:300459782788:android:e6a15d4c8d996153d788d1',
    messagingSenderId: '300459782788',
    projectId: 'prueba-66e48',
    storageBucket: 'prueba-66e48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKA-m-1046iTs0wQOCXgX3LokSRKVENUQ',
    appId: '1:300459782788:ios:1851b5d8af93e587d788d1',
    messagingSenderId: '300459782788',
    projectId: 'prueba-66e48',
    storageBucket: 'prueba-66e48.appspot.com',
    iosClientId: '300459782788-cbfsu98hbod0pc5pqfr2td09v3ek2blg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPrueba',
  );
}
